name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v2.1.4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Download APK
      uses: actions/download-artifact@v2.0.5
      id: download
      with:
        name: 'app'
        path: artifacts/android
    - name: Distribute to App Center
      uses: wzieba/AppCenter-Github-Action@v1.2.1
      with:
        appName: LearnProgrammingAcademy/Example
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Beta Testers
        run: echo ${{steps.download.outputs.download-path}}
        file: ${{steps.download.outputs.download-path}}
        notifyTesters: true
